sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 6

notifications:
  email:
    - medikoo+dbjs-dom@medikoo.com

script: "npm run lint"
